### PR TITLE
(feature) Add token support for private repos

### PR DESCRIPTION
**Pull request by DomiR**

### CODE REVIEW

**Comment by dylang** [comment]
Great idea. I'm not sure what work is needed, do you want to look into it?

**Comment by DomiR** [comment]
Do you mean me? The pull-request has this already implemented. One just need to pass the token from the cli options. You can decide if you like the passing style or if you want to pass the whole options object so we could do something like --sort="FEAT,FIX,CLEAN" or something to even sort the changes...

Nice job on this tool, I like it :+1:

**Comment by dylang** [comment]
Oh, nice, I didn't notice the pull request when I saw this before. I hope to review it this weekend.

**Comment by DomiR** [comment]
It would be fancy to be able to group by some terms like `FEAT,FIX,CLEAN` etc. 
Maybe pass this as `--group "FEAT,FIX,CLEAN"` with comma separated search strings or maybe even regex expressions (would need to escape commas in expression: `--group "comma\,expression,noncomma-expression"` then split with `terms.split(/[^\\],/)`). Instead of regex maybe a flag to only look for keywords in the prefix of change message. 

You can also look at this, where I hard-coded this: 
https://github.com/DomiR/changelog/blob/groupby/lib/datasrc/github.js#L49

**Comment by DomiR** [comment]
Would you mind merging this?

**Comment by albertfdp** [comment]
@dylang any plans to merge this in? Also, it will allow to do more API calls, as the api rate limit is larger when using authenticated calls

**Comment by rarkins** [comment]
Hi @DomiR, thank you for this Pull Request. Could you confirm if either:

1. You no longer require this project/feature, or
2. You can use process.env.GITHUB_TOKEN as implemented in https://github.com/dylang/changelog/pull/24/files ?

**Comment by DomiR** [comment]
thanks, won't be needing this any time soon

**Comment by rarkins** [comment]
Also cc @albertfdp

**Pull request closed without merging**
